# Generated by Django 6.0.7 on 2026-09-03 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва події')),
                ('description', models.TextField(verbose_name='Опис події')),
                ('start_datetime', models.DateTimeField(verbose_name='Дата та час початку')),
                ('end_datetime', models.DateTimeField(verbose_name='Дата та час закінчення')),
                ('location', models.CharField(max_length=255, verbose_name='Місце проведення')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Фотографія')),
                ('online_link', models.URLField(blank=True, verbose_name='Посилання на онлайн-подію')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Організатор')),
            ],
            options={
                'verbose_name': 'Подія',
                'verbose_name_plural': 'Події',
                'ordering': ['start_datetime'],
            },
        ),
    ]
